apiVersion: v1
kind: Service
metadata:
  name: feedback-backend-service
spec:
  selector:
    app: feedback-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
